openapi: 3.0.4

info:
   title: My First API
   
   description: Hello World
   version: 1.0.0
   
servers:
  - url: http://dev.test.com/v1
    description: Optional server description, e.g. Main (development) server
  - url: http://uat.test.com/v1
    description: Optional server description, e.g. Internal staging server for testing
   
tags:
  - name: customer
    description: CRM Object
    
paths:
  /addresses:
     get:
        tags:
          - address
        summary: Get All Addresses
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    Customer:
                      type: array
                      items:
                        $ref: '#/components/schemas/Address'
  /customers:
     get:
        tags:
          - customer
        summary: Get All Customers
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    Customer:
                      type: array
                      items:
                        $ref: '#/components/schemas/Customer'
            

components:
  schemas:
     Customer:
      type: object
      properties:
        id:
          type: string
        street:
          type: string
        
     Address:
      type: object
      properties:
        id:
          type: string
        street:
          type: string
